name: QA Automation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "SuperSecretQA_Password123!"
        ports:
          - "1433:1433"

    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Configurar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Configurar Node.js (Newman)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias globales
        run: |
          npm install -g newman
          dotnet tool install --global dotnet-ef

      - name: Fase 1 - Pruebas Unitarias e Integracion
        run: dotnet test

      - name: Preparar Base de Datos SQL Server
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet ef database update --project FraudGuard.Infrastructure --startup-project FraudGuard.API

      - name: Fase 2 - Pruebas E2E (API + Newman)
        # TRUCO SDET: Corremos la API y los test en el mismo paso para que GitHub no apague el servidor.
        run: |
          echo "Iniciando la API en segundo plano..."
          dotnet run --project FraudGuard.API &
          
          echo "Esperando 10 segundos para que el servidor despierte..."
          sleep 10
          
          echo "Ejecutando pruebas automatizadas de Postman con Newman..."
          newman run postman_collection.json